---
name: megapixelmontage
region: tor

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: megapixelmontage
      match:
        authority:
          exact: ""
        path:
          prefix: /

services:
  - build_command: npm run build
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
    github:
      branch: main
      repo: mikemimik/megapixelmontage
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: megapixelmontage
    run_command: node server.js
    source_dir: /
    health_check:
      initial_delay_seconds: 30
      success_threshold: 2
      http_path: /healthcheck
